INSERT INTO speciality (description) VALUES ('Cardiology');
INSERT INTO speciality (description) VALUES ('Dermatology');
INSERT INTO speciality (description) VALUES ('Endocrinology');
INSERT INTO speciality (description) VALUES ('Gastroenterology');
INSERT INTO speciality (description) VALUES ('Hematology');
INSERT INTO speciality (description) VALUES ('Neurology');
INSERT INTO speciality (description) VALUES ('Oncology');
INSERT INTO speciality (description) VALUES ('Pediatrics');
INSERT INTO speciality (description) VALUES ('Psychiatry');
INSERT INTO speciality (description) VALUES ('Radiology');
INSERT INTO speciality (description) VALUES ('Allergy and Immunology');
INSERT INTO speciality (description) VALUES ('Anesthesiology');
INSERT INTO speciality (description) VALUES ('Cardiothoracic Surgery');
INSERT INTO speciality (description) VALUES ('Critical Care Medicine');
INSERT INTO speciality (description) VALUES ('Emergency Medicine');